apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-metrics-mirror
  namespace: monitoring
  labels:
    # МЕТКА ТУТ: Она связывает этот Сервис с ServiceMonitor ниже
    mirror: ingress-nginx
spec:
  ports:
  - port: 10254
    targetPort: 10254
    name: metrics
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ingress-nginx-metrics-mirror
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.98.178.127  # Ваш ClusterIP сервиса метрик из ingress-nginx
  ports:
  - port: 10254
    name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-metrics-mirror-sm
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - monitoring       # Prometheus ищет только внутри своего неймсейса
  selector:
    matchLabels:
      mirror: ingress-nginx  # И находит наш зеркальный Сервис по метке
