[control_plane]
control1 ansible_host= ansible_user=ubuntu
control2 ansible_host= ansible_user=ubuntu
control3 ansible_host= ansible_user=ubuntu

[workers]
worker1 ansible_host= ansible_user=ubuntu

[lb]
lb1 ansible_host= ansible_user=ubuntu

[all:vars]
StrictHostKeyChecking=no
ansible_python_interpreter=/usr/bin/python3
private_key_file=/root/k8s_final/structure/ansible/id_rsa